version: 1.0
name: Naruto
main: de.luke.naruto.Main
author: Vator
description: Demo Plugin
commands:
  menu:
    aliases: [mn]
    description: Menu command

  claim:
    aliases: [cl]
    description: Claim command

